// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Register struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
